version: '3.7'

services:
  backend:
    container_name: app
    build: .
    restart: always
    ports:
      - ${BACKEND_PORT}:${BACKEND_INNER_PORT}
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:5.7
    platform: linux/amd64
    # image: mysql/mysql-server # Apple M1
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ./go-clicli.sql:/docker-entrypoint-initdb.d/clicli.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: unless-stopped